model_list:
model_list:
  - model_name: bedrock-converse-us-claude-3-7-sonnet-v1
    litellm_params:
      model: bedrock/converse/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_region_name: os.environ/AWS_REGION_NAME
      aws_session_name: "claude-3-7-sonnet-session"

  - model_name: bedrock-us-claude-3-5-sonnet-v2
    litellm_params:
      model: bedrock/converse/us.anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_region_name: os.environ/AWS_REGION_NAME
      aws_session_name: "claude-3-5-sonnet-v2-us-session"
  
  - model_name: bedrock-apac-claude-3-5-sonnet-v2
    litellm_params:
      model: bedrock/converse/apac.anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_region_name: ap-northeast-1
      aws_session_name: "claude-3-5-sonnet-v2-apac-session"
  
  - model_name: bedrock-claude-3-5-sonnet-v1
    litellm_params:
       model: bedrock/converse/anthropic.claude-3-5-sonnet-20240620-v1:0
       aws_region_name: os.environ/AWS_REGION_NAME
       aws_session_name: "claude-3-5-sonnet-v1-session"

  - model_name: bedrock-converse-us-deepseek-r1-v1
    litellm_params:
      model: bedrock/converse/us.deepseek.r1-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_NAME

  - model_name: bedrock-converse-us-nova-pro-v1
    litellm_params:
      model: bedrock/converse/us.amazon.nova-pro-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_NAME

  - model_name: bedrock-converse-apac-nova-pro-v1
    litellm_params:
      model: bedrock/converse/apac.amazon.nova-pro-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: ap-northeast-1

litellm_settings:
  fallbacks: [
    {"bedrock-converse-us-claude-3-7-sonnet-v1": 
      [
        "bedrock-us-claude-3-5-sonnet-v2",
        "bedrock-apac-claude-3-5-sonnet-v2",
      ]
    }
  ]
  num_retries: 2
  request_timeout: 30
  aws_region_name: os.environ/AWS_REGION_NAME
  aws_session_name: "litellm-bedrock-session"
  drop_params: true # サポート外のパラメータを無視する

general_settings:
  log_level: debug
  openai_api_base: "/v1"
  disable_user_auth: true  # 開発中は認証を無効化（本番環境では使用しないでください）

router_settings:
  default_model: bedrock-converse-us-claude-3-7-sonnet-v1
  failover: true
  timeout: 30
  retries: 3

openapi:
  openapi_version: "3.1.0"
  title: "LiteLLM API"
  description: "LiteLLM API for multiple LLM models"
  servers:
    - url: "/"
  info:
    version: "1.0.0"

guardrails:
  - guardrail_name: "custom-pre-guard"
    litellm_params:
      guardrail: custom_guardrail.SecurityGuardrail
      mode: "pre_call"

  - guardrail_name: "custom-during-guard"
    litellm_params:
      guardrail: custom_guardrail.SecurityGuardrail
      mode: "during_call"

  - guardrail_name: "custom-post-guard"
    litellm_params:
      guardrail: custom_guardrail.SecurityGuardrail
      mode: "post_call"

  - guardrail_name: "presidio-pre-guard"
    litellm_params:
      guardrail: presidio
      mode: "pre_call"
      output_parse_pii: true

  - guardrail_name: "presidio-post-guard"
    litellm_params:
      guardrail: presidio
      mode: "post_call"
      output_parse_pii: true
