[project]
name = "my-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "autogen>=0.7.2",
    "langgraph>=0.2.67",
    "langgraph-cli>=0.1.68",
]

[dependency-groups]
dev = [
    "langgraph-cli>=0.1.68",
]
