model_list:
  - model_name: bedrock-converse-us-claude-3-7-sonnet-v1
    litellm_params:
      model: bedrock/converse/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_region_name: os.environ/AWS_REGION_NAME
      aws_session_name: "claude-3-7-sonnet-session"
      #thinking: {"type": "enabled", "budget_tokens": 1024}

  - model_name: bedrock-us-claude-3-5-sonnet-v2
    litellm_params:
      model: bedrock/converse/us.anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_region_name: os.environ/AWS_REGION_NAME
      aws_session_name: "claude-3-5-sonnet-v2-us-session"
  
  - model_name: bedrock-apac-claude-3-5-sonnet-v2
    litellm_params:
      model: bedrock/converse/apac.anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_region_name: ap-northeast-1
      aws_session_name: "claude-3-5-sonnet-v2-apac-session"
  
  - model_name: bedrock-claude-3-5-sonnet-v1
    litellm_params:
       model: bedrock/converse/anthropic.claude-3-5-sonnet-20240620-v1:0
       aws_region_name: os.environ/AWS_REGION_NAME
       aws_session_name: "claude-3-5-sonnet-v1-session"

litellm_settings:
  fallbacks: [
    {"bedrock-converse-us-claude-3-7-sonnet-v1": 
      [
        "bedrock-us-claude-3-5-sonnet-v2",
        "bedrock-apac-claude-3-5-sonnet-v2",
        "bedrock-claude-3-5-sonnet-v1"
      ]
    }
  ]
  num_retries: 2
  request_timeout: 30
  aws_region_name: os.environ/AWS_REGION_NAME
  aws_session_name: "litellm-bedrock-session"
  drop_params: true # サポート外のパラメータを無視する

general_settings:
  log_level: debug
  openai_api_base: "/v1"
  disable_user_auth: true  # 開発中は認証を無効化（本番環境では使用しないでください）

router_settings:
  default_model: bedrock-converse-us-claude-3-7-sonnet-v1
  failover: true
  timeout: 30
  retries: 3

openapi:
  openapi_version: "3.1.0"
  title: "LiteLLM API"
  description: "LiteLLM API for multiple LLM models"
  servers:
    - url: "/"
  info:
    version: "1.0.0"

# MCP Servers Configuration
mcp_servers:
  "github.com/upstash/context7-mcp":
    command: "npx"
    args: ["-y", "@upstash/context7-mcp@latest"]
    autoApprove: []
    disabled: false
    timeout: 60
    transportType: "stdio"
  
  "github.com/awslabs/mcp/tree/main/src/aws-documentation-mcp-server":
    command: "uvx"
    args: ["awslabs.aws-documentation-mcp-server@latest"]
    autoApprove: []
    disabled: false
    timeout: 60
    transportType: "stdio"
