version: "3"
services:
  notebook:
    build: ./docker_images/jupyter
    ports:
      - "8080:8080"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    working_dir: /home/root/work
    volumes:
      - ./work:/home/root/work
    command: jupyter notebook --port 8080 --notebook-dir="/home/root/work" --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token="$TOKEN"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always